services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", ""] 
  api:
    build:
      context: .
      dockerfile: Dockerfile  # Your .NET API Dockerfile
    environment:
      - REDIS_CONNECTION=redis:6379
    ports:
      - "8081:8081"  # Map to the API's default port
    
    depends_on:
      - redis  # Ensure Redis starts before the API